"""create initial schema

Revision ID: 35fca2916818
Revises: 
Create Date: 2026-02-17 23:50:07.375037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35fca2916818'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('student', 'instructor')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('weight_io', sa.Integer(), nullable=False),
    sa.Column('weight_unit', sa.Integer(), nullable=False),
    sa.Column('weight_static', sa.Integer(), nullable=False),
    sa.Column('max_runtime_ms', sa.Integer(), nullable=False),
    sa.Column('max_memory_kb', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(weight_io + weight_unit + weight_static) = 100', name='ck_assignment_weights_sum_100'),
    sa.CheckConstraint('weight_io >= 0 AND weight_unit >= 0 AND weight_static >= 0', name='ck_assignment_weights_nonneg'),
    sa.ForeignKeyConstraint(['instructor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_instructor_id'), 'assignments', ['instructor_id'], unique=False)
    op.create_table('io_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('stdin', sa.Text(), nullable=True),
    sa.Column('expected_stdout', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_io_test_cases_assignment_id'), 'io_test_cases', ['assignment_id'], unique=False)
    op.create_table('static_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('required_functions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('forbidden_imports', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('max_cyclomatic_complexity', sa.Integer(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_rules_assignment_id'), 'static_rules', ['assignment_id'], unique=True)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('code_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('latest_grading_run_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'running', 'completed', 'failed')", name='ck_submissions_status'),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['latest_grading_run_id'], ['grading_runs.id'], name='fk_submissions_latest_grading_run', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assignment_id'), 'submissions', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    op.create_table('unit_test_specs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('test_code', sa.Text(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_unit_test_specs_assignment_id'), 'unit_test_specs', ['assignment_id'], unique=True)
    op.create_table('grading_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('io_score', sa.Integer(), nullable=False),
    sa.Column('unit_score', sa.Integer(), nullable=False),
    sa.Column('static_score', sa.Integer(), nullable=False),
    sa.Column('score_total', sa.Integer(), nullable=False),
    sa.Column('judge0_io_tokens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('judge0_unit_token', sa.Text(), nullable=True),
    sa.Column('feedback_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_feedback', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running', 'completed', 'failed')", name='ck_grading_runs_status'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grading_runs_submission_id'), 'grading_runs', ['submission_id'], unique=False)
    op.create_table('static_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grading_run_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cyclomatic_complexity', sa.Integer(), nullable=True),
    sa.Column('radon_report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grading_run_id'], ['grading_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_static_analysis_reports_grading_run_id'), 'static_analysis_reports', ['grading_run_id'], unique=True)
    op.create_table('test_case_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grading_run_id', sa.Integer(), nullable=False),
    sa.Column('io_test_case_id', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('stdout', sa.Text(), nullable=True),
    sa.Column('stderr', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('time_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['grading_run_id'], ['grading_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['io_test_case_id'], ['io_test_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grading_run_id', 'io_test_case_id', name='uq_test_case_results_run_case')
    )
    op.create_index(op.f('ix_test_case_results_grading_run_id'), 'test_case_results', ['grading_run_id'], unique=False)
    op.create_index(op.f('ix_test_case_results_io_test_case_id'), 'test_case_results', ['io_test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_results_io_test_case_id'), table_name='test_case_results')
    op.drop_index(op.f('ix_test_case_results_grading_run_id'), table_name='test_case_results')
    op.drop_table('test_case_results')
    op.drop_index(op.f('ix_static_analysis_reports_grading_run_id'), table_name='static_analysis_reports')
    op.drop_table('static_analysis_reports')
    op.drop_index(op.f('ix_grading_runs_submission_id'), table_name='grading_runs')
    op.drop_table('grading_runs')
    op.drop_index(op.f('ix_unit_test_specs_assignment_id'), table_name='unit_test_specs')
    op.drop_table('unit_test_specs')
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assignment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_static_rules_assignment_id'), table_name='static_rules')
    op.drop_table('static_rules')
    op.drop_index(op.f('ix_io_test_cases_assignment_id'), table_name='io_test_cases')
    op.drop_table('io_test_cases')
    op.drop_index(op.f('ix_assignments_instructor_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
